local LSM = LibStub("LibSharedMedia-3.0")
-- -----
--   SOUND
-- -----
LSM:Register("sound", "|c0092ff0050DKP|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\50DKP.ogg]])
LSM:Register("sound", "|c0092ff00fuckyou狗一波|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\fuckyou-gouyibo.ogg]])
LSM:Register("sound", "|c0092ff00kiumi!@#$%|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\kiumi!@#$%.ogg]])
LSM:Register("sound", "|c0092ff00liveking|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\liveking.ogg]])
LSM:Register("sound", "|c0092ff00shitbro|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\shitbro.ogg]])
LSM:Register("sound", "|c0092ff00whatde|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\whatde.ogg]])
LSM:Register("sound", "|c0092ff00ymind!@#$%|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\ymind!@#$%.ogg]])
LSM:Register("sound", "|c0092ff00不会黑了吧|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\buhuiheileba.ogg]])
LSM:Register("sound", "|c0092ff00你快回来|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\nikuaihuilai.ogg]])
LSM:Register("sound", "|c0092ff00你过来呀|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\niguolaiya.ogg]])
LSM:Register("sound", "|c0092ff00你过来呀baomei|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\niguolaiyabaomei.ogg]])
LSM:Register("sound", "|c0092ff00卡了卡了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\kalekale.ogg]])
LSM:Register("sound", "|c0092ff00吃屎|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\chishi.ogg]])
LSM:Register("sound", "|c0092ff00呕吐|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\outu.ogg]])
LSM:Register("sound", "|c0092ff00哈嘿嘻|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\haheixi.ogg]])
LSM:Register("sound", "|c0092ff00好变态啊|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\haobiantaia.ogg]])
LSM:Register("sound", "|c0092ff00完了啊WTF|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\wanleaWTF.ogg]])
LSM:Register("sound", "|c0092ff00怀疑nmb|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\huaiyinmb.ogg]])
LSM:Register("sound", "|c0092ff00怎么又死了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\zenmeyousile.ogg]])
LSM:Register("sound", "|c0092ff00我开星界了啊|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\wokaixingjielea.ogg]])
LSM:Register("sound", "|c0092ff00拉屎nmb|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\lashinmb.ogg]])
LSM:Register("sound", "|c0092ff00救救我|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\jiujiuwo.ogg]])
LSM:Register("sound", "|c0092ff00救救我susu|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\jiujiuwosusu.ogg]])
LSM:Register("sound", "|c0092ff00求生欲|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\qiushengyu.ogg]])
LSM:Register("sound", "|c0092ff00点掉了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\diandiaole.ogg]])
LSM:Register("sound", "|c0092ff00牛逼|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\niubi.ogg]])
LSM:Register("sound", "|c0092ff00粉红色的|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\fenhongsede.ogg]])
LSM:Register("sound", "|c0092ff00老骑士装备|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\laoqishizhuangbei.ogg]])
LSM:Register("sound", "|c0092ff00这都过了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\zhedouguole.ogg]])
LSM:Register("sound", "|c0092ff00都怪狗一波|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\douguaigouyibo.ogg]])
LSM:Register("sound", "|c0092ff00驱啊驱啊卧槽|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\quaqua.ogg]])
LSM:Register("sound", "|c0092ff00鸭屎啊你|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\yashiani.ogg]])
LSM:Register("sound", "|c0092ff00啊FUCK|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\afuck.ogg]])
LSM:Register("sound", "|c0092ff00啊卧槽no|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\awocaono.ogg]])
LSM:Register("sound", "|c0092ff00dongdongdong|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\dongdongdong.ogg]])
LSM:Register("sound", "|c0092ff00nice|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\nice.ogg]])
LSM:Register("sound", "|c0092ff00屎洞大大|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\shidongdada.ogg]])
LSM:Register("sound", "|c0092ff00sirsirsir|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\sirsirsir.ogg]])
LSM:Register("sound", "|c0092ff00我开星界了啊lanko|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\wokaixingjielea-lanko.ogg]])
LSM:Register("sound", "|c0092ff00我磕合剂|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\wokeheji.ogg]])
LSM:Register("sound", "|c0092ff00dingdongduang|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\dingdongduang.ogg]])
LSM:Register("sound", "|c0092ff00dio cnm-dashu|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\diocnm.ogg]])
LSM:Register("sound", "|c0092ff00FK U狗一波|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\fuckyougouyibo.ogg]])
LSM:Register("sound", "|c0092ff00嗝嗝嗝嗝嗝嗝|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\gegegegegege.ogg]])
LSM:Register("sound", "|c0092ff00喜欢赢的感觉|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\xihuanyingdeganjue.ogg]])
LSM:Register("sound", "|c0092ff00做梦去吧|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\zuomengquba.ogg]])
LSM:Register("sound", "|c0092ff00dio cnm-98|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\diocnm-98.ogg]])