local LSM = LibStub("LibSharedMedia-3.0")
-- -----
--   SOUND
-- -----
LSM:Register("sound", "|c0092ff0050DKP|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\50DKP.ogg]])
LSM:Register("sound", "|c0092ff00fuckyou狗一波|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\fuckyou狗一波.ogg]])
LSM:Register("sound", "|c0092ff00kiumi!@#$%|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\kiumi!@#$%.ogg]])
LSM:Register("sound", "|c0092ff00liveking|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\liveking.ogg]])
LSM:Register("sound", "|c0092ff00shitbro|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\shitbro.ogg]])
LSM:Register("sound", "|c0092ff00whatde|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\whatde.ogg]])
LSM:Register("sound", "|c0092ff00ymind!@#$%|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\ymind!@#$%.ogg]])
LSM:Register("sound", "|c0092ff00不会黑了吧|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\不会黑了吧.ogg]])
LSM:Register("sound", "|c0092ff00你快回来|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\你快回来.ogg]])
LSM:Register("sound", "|c0092ff00你过来呀|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\你过来呀.ogg]])
LSM:Register("sound", "|c0092ff00你过来呀baomei|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\你过来呀baomei.ogg]])
LSM:Register("sound", "|c0092ff00卡了卡了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\卡了卡了.ogg]])
LSM:Register("sound", "|c0092ff00吃屎|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\吃屎.ogg]])
LSM:Register("sound", "|c0092ff00呕吐|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\呕吐.ogg]])
LSM:Register("sound", "|c0092ff00哈嘿嘻|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\哈嘿嘻.ogg]])
LSM:Register("sound", "|c0092ff00好变态啊|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\好变态啊.ogg]])
LSM:Register("sound", "|c0092ff00完了啊WTF|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\完了啊WTF.ogg]])
LSM:Register("sound", "|c0092ff00怀疑nmb|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\怀疑nmb.ogg]])
LSM:Register("sound", "|c0092ff00怎么又死了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\怎么又死了.ogg]])
LSM:Register("sound", "|c0092ff00我开星界了啊|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\我开星界了啊.ogg]])
LSM:Register("sound", "|c0092ff00拉屎nmb|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\拉屎nmb.ogg]])
LSM:Register("sound", "|c0092ff00救救我|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\救救我.ogg]])
LSM:Register("sound", "|c0092ff00救救我susu|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\救救我susu.ogg]])
LSM:Register("sound", "|c0092ff00求生欲|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\求生欲.ogg]])
LSM:Register("sound", "|c0092ff00点掉了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\点掉了.ogg]])
LSM:Register("sound", "|c0092ff00牛逼|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\牛逼.ogg]])
LSM:Register("sound", "|c0092ff00粉红色的|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\粉红色的.ogg]])
LSM:Register("sound", "|c0092ff00老骑士装备|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\老骑士装备.ogg]])
LSM:Register("sound", "|c0092ff00这都过了|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\这都过了.ogg]])
LSM:Register("sound", "|c0092ff00都怪狗一波|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\都怪狗一波.ogg]])
LSM:Register("sound", "|c0092ff00驱啊驱啊卧槽|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\驱啊驱啊卧槽.ogg]])
LSM:Register("sound", "|c0092ff00鸭屎啊你|r", [[Interface\Addons\SharedMedia_ScarletConservative\sound\鸭屎啊你.ogg]])
